#!/usr/bin/python

# -*- coding: utf-8 -*-
import re
import sys
import site

sys.path.insert(0,site.getsitepackages()[0])

from sphinx import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
